# Generated by Django 5.2 on 2025-04-11 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VMapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='file',
            new_name='video_file',
        ),
    ]
